In [1]:
from sklearn import preprocessing

In [2]:
le=preprocessing.LabelEncoder()

In [3]:
import pandas as pd

In [4]:
data=pd.read_csv('data.csv')

In [5]:
data

color    type    origin stolen
0     red  sports  domestic    yes
1     red  sports  domestic     no
2     red  sports  domestic    yes
3  yellow  sports  domestic     no
4  yellow  sports  imported    yes
5  yellow     suv  imported     no
6  yellow     suv  imported    yes
7  yellow     suv  domestic     no
8     red     suv  imported     no
9     red  sports  imported    yes

In [6]:
features=[feat for feat in data]

In [7]:
features

['color', 'type', 'origin', 'stolen']

In [8]:
for feat in data:
    print(feat)

color
type
origin
stolen


In [10]:
data['color']

0       red
1       red
2       red
3    yellow
4    yellow
5    yellow
6    yellow
7    yellow
8       red
9       red
Name: color, dtype: object

In [11]:
diff_values=[]
for f in features:
    for v in data[f]:
        print(v)

red
red
red
yellow
yellow
yellow
yellow
yellow
red
red
sports
sports
sports
sports
sports
suv
suv
suv
suv
sports
domestic
domestic
domestic
domestic
imported
imported
imported
domestic
imported
imported
yes
no
yes
no
yes
no
yes
no
no
yes


In [13]:
diff_values=[]
for f in features:
    for v in data[f]:
        if v not in diff_values:
            diff_values.append(v)

diff_values

['red', 'yellow', 'sports', 'suv', 'domestic', 'imported', 'yes', 'no']

In [14]:
le.fit(diff_values)

LabelEncoder()

In [15]:
list(le.classes_)

['domestic', 'imported', 'no', 'red', 'sports', 'suv', 'yellow', 'yes']

In [16]:
import numpy as np
dataArray=np.array(data)

In [17]:
dataArray

array([['red', 'sports', 'domestic', 'yes'],
       ['red', 'sports', 'domestic', 'no'],
       ['red', 'sports', 'domestic', 'yes'],
       ['yellow', 'sports', 'domestic', 'no'],
       ['yellow', 'sports', 'imported', 'yes'],
       ['yellow', 'suv', 'imported', 'no'],
       ['yellow', 'suv', 'imported', 'yes'],
       ['yellow', 'suv', 'domestic', 'no'],
       ['red', 'suv', 'imported', 'no'],
       ['red', 'sports', 'imported', 'yes']], dtype=object)

In [18]:
dataArray.shape

(10, 4)

In [19]:
le.transform(dataArray[0])

array([3, 4, 0, 7])

# Experiment complete

In [22]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [23]:
le=preprocessing.LabelEncoder()
data=pd.read_csv('data.csv')

In [20]:
features=[feat for feat in data]
features.remove('stolen')
features

['color', 'type', 'origin']

In [21]:
diff_values=[]
for f in features:
    for v in data[f]:
        if v not in diff_values:
            diff_values.append(v)

diff_values

['red', 'yellow', 'sports', 'suv', 'domestic', 'imported']

In [26]:
dataArray=np.array(data.iloc[:,0:-1])
dataArray

array([['red', 'sports', 'domestic'],
       ['red', 'sports', 'domestic'],
       ['red', 'sports', 'domestic'],
       ['yellow', 'sports', 'domestic'],
       ['yellow', 'sports', 'imported'],
       ['yellow', 'suv', 'imported'],
       ['yellow', 'suv', 'imported'],
       ['yellow', 'suv', 'domestic'],
       ['red', 'suv', 'imported'],
       ['red', 'sports', 'imported']], dtype=object)

In [28]:
le.fit(diff_values)
list(le.classes_)

['domestic', 'imported', 'red', 'sports', 'suv', 'yellow']

In [33]:
trans=[]
for d in dataArray:
    trans.append(le.transform(d))
trans

array([[2, 3, 0],
       [2, 3, 0],
       [2, 3, 0],
       [5, 3, 0],
       [5, 3, 1],
       [5, 4, 1],
       [5, 4, 1],
       [5, 4, 0],
       [2, 4, 1],
       [2, 3, 1]])

In [34]:
target=data['stolen']
target

0    yes
1     no
2    yes
3     no
4    yes
5     no
6    yes
7     no
8     no
9    yes
Name: stolen, dtype: object

In [35]:
target=np.array(target)

In [37]:
tar=[]
for t in target:
    if t == "yes":
        tar.append(1)
    else:
        tar.append(0)
tar

[1, 0, 1, 0, 1, 0, 1, 0, 0, 1]

# Running Multinomial theorem

In [38]:
from sklearn.naive_bayes import MultinomialNB

In [39]:
clf = MultinomialNB()

In [40]:
clf.fit(trans,tar)

MultinomialNB()

# trying to predict

In [46]:
predicting=["red","suv","domestic"]
pre_array=le.transform(predicting)

In [62]:
pre_array=np.reshape(pre_array,(1,3))
pre_array

array([[2, 4, 0]])

In [63]:
print(clf.predict(pre_array))

[0]


In [50]:
print(clf.predict(trans[0:1]))

[0]


In [51]:
trans[0:1]

array([[2, 3, 0]])